# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

version: "2"

run:
  timeout: 5m

output:
  formats:
    colored-line-number: {}

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/crossplane/function-auto-ready

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false

    govet:
      check-shadowing: false

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - errcheck

issues:
  new: false
  max-per-linter: 0
  max-same-issues: 0
